config/paths.js
config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
scripts/build.js
src/index.js
src/libs/coordinatorLib.js

This is in preparation for initial publication of the library for early testing. Nothing particularly interesting here.
@justinaray @jrrucker @JackieChiles @omarestrella @xdumaine

Update package.json, remove unnecessary build steps

---

README.md
js/iframe-coordinator/package-lock.json
js/iframe-coordinator/package.json

[Rendered README](https://github.com/purecloudlabs/iframe-coordinator/blob/add-docs/README.md)

Add some basic docs

---

js/iframe-coordinator/elements/frame-router.ts
js/iframe-coordinator/elements/x-ifc-frame.ts

My takeaway here: Never do _anything_ in a custom element constructor.

Move all DOM work out of custom element constructors.

---

js/demo-app/package-lock.json
js/demo-app/package.json
js/demo-app/public/components/example1/index.html
js/demo-app/public/components/example2/index.html
js/demo-app/public/demo.css
js/demo-app/public/index.html
js/demo-app/src/component.js
js/demo-app/src/index.js
js/demo-app/webpack.config.js
js/iframe-coordinator/elements/frame-router.ts
js/iframe-coordinator/elm/Host.elm
js/iframe-coordinator/libs/client.ts
src/ClientMessage.elm
src/ClientProgram.elm
src/HostProgram.elm
src/Message/Toast.elm

Add toast message support

---

.gitignore
js/iframe-coordinator/.gitignore
scripts/jenkins.sh

Add npm-utils to root .gitignore
Add .npmrc to js lib .gitignore
Remove npm-utils before cloning
Bump package version to test build

Fixed build to push tag and version bump back to SCM

---

js/iframe-coordinator/Elm.d.ts
js/iframe-coordinator/elements/frame-router.ts
js/iframe-coordinator/libs/client.ts
js/iframe-coordinator/libs/types.ts
js/iframe-coordinator/tsconfig.json

Always open for more improvements or reorg, but this gets us a bit closer to ideal.

Adding better types for the Elm modules

---

js/demo-app/public/components/example1/index.html
js/demo-app/public/components/example2/index.html
js/demo-app/public/demo.css
js/demo-app/public/index.html
js/demo-app/src/index.js

* Convert url/programmatic nav into an exclusive state with a toggle
* Add active top-level nav styling to make routing more obvious
* Add labels in component html to make the examples a bit easier to grok
* Default to the first defined route on initial load, if needed
* Dynamically generate nav menus and register routes from the same nav definition
* Styled Header, nav, routing option toggle, and publish button
* Removed state and helpers from window as the listeners are attached in js
* Demo js code organization and comments

Make the demo a bit clearer {READY_FOR_REVIEW}

---

elm.json
js/iframe-coordinator/elm/Client.elm
js/iframe-coordinator/elm/Host.elm
js/iframe-coordinator/package-lock.json
js/iframe-coordinator/package.json
scripts/test.sh
src/ClientProgram.elm
src/HostProgram.elm
src/Message/AppToClient.elm
src/Message/AppToHost.elm
src/Message/ClientToApp.elm
src/Message/ClientToHost.elm
src/Message/HostToApp.elm
src/Message/HostToClient.elm
src/Message/Navigation.elm
src/Message/PubSub.elm
src/Message/Toast.elm
tests/Fixture/ToastMessage.elm
tests/ToastMessage.elm

Publication to the elm package system gives us enforced semver, but
there are other requirements to meet as well, like having docs and
making sure the code doesn't rely on the Debug module, which can't be
used in an optimised build.

Prepare library for publication.

---

README.md
js/demo-app/src/component.js
js/demo-app/src/index.js
js/iframe-coordinator/Elm.d.ts
js/iframe-coordinator/libs/client.ts
js/iframe-coordinator/libs/host.ts
js/iframe-coordinator/libs/index.ts

Pretty simple rework, just to make sure the idea/coding style is agreed upon.  I also want to add some tests as part of this, since I wish I had that to confirm everything worked.

Converting client into a class structure.

---

js/demo-app/public/demo.css
js/demo-app/public/index.html
js/demo-app/src/index.js

buttons will look like tabs ;)

adding same styling for programmatic routing

---

js/demo-app/package-lock.json
js/demo-app/package.json
js/demo-app/src/component.js
js/demo-app/src/index.js
js/demo-app/webpack.config.js

Was able to get the demo app and library running in Edge.  IE11 app is up and limping along, but the cross-frame events are getting lost.  This was good progress so I wanted to go ahead and open this one.

Feature/improve demo ie support {READY_FOR_REVIEW}

---

js/iframe-coordinator/.gitignore
js/iframe-coordinator/package-lock.json
js/iframe-coordinator/package.json
js/iframe-coordinator/src/HostRouter.ts
js/iframe-coordinator/src/SubscriptionManager.ts
js/iframe-coordinator/src/client.ts
js/iframe-coordinator/src/elements/frame-router.ts
js/iframe-coordinator/src/elements/x-ifc-frame.ts
js/iframe-coordinator/src/host.ts
js/iframe-coordinator/src/messages/ClientToHost.ts
js/iframe-coordinator/src/messages/HostToClient.ts
js/iframe-coordinator/src/messages/LabeledMsg.ts
js/iframe-coordinator/src/messages/NavRequest.ts
js/iframe-coordinator/src/messages/Publication.ts
js/iframe-coordinator/src/messages/Toast.ts
js/iframe-coordinator/src/types.ts
js/iframe-coordinator/tslint.json

This beings the process of adding tsdoc places.  I still haven't figured out everything... For example the @link's aren't working.  However, I figured its still worthwhile to get initial feedback.
I still have various things to turn on in the tslint config as well.  I will finish that out tomorrow.

Initial take on documentation.  

---

README.md
demo-app/package-lock.json
demo-app/package.json
demo-app/public/components/example1/index.html
demo-app/public/components/example2/index.html
demo-app/src/component.js
demo-app/src/index.js
package-lock.json
package.json
src/EventEmitter.ts
src/FrameManager.ts
src/client.ts
src/elements/frame-router.ts
src/messages/ClientToHost.ts
src/messages/HostToClient.ts
src/messages/Lifecycle.ts
src/messages/Publication.ts
src/messages/specs/HostToClient.spec.ts
src/specs/EventEmitter.spec.ts
src/specs/FrameManager.spec.ts
src/specs/client.spec.ts
tslint.json

Still a work in progress, but I wanted to put this up in case anyone wanted to give feedback on this API.

Better pub/sub API?

---

.npmrc
package-lock.json
package.json
scripts/buildlibs.sh
scripts/jenkins.sh

Also adds some better tooling for pushing back tags and commits from
Jenkins.

Update build process to handle migration to TypeScript

---

src/FrameManager.ts

Came across a few edge cases while working on something else.  Figured I'd add them in a sep PR.

Handle a few invalid origin edge cases

---

demo-app/src/index.js

The demo app had a bug where it was failing to apply the fragment route
to the frame-router element after a reload. This fixes that issue.

Fix demo app failing to initialize fragment route correctly.

---

README.md
demo-app/src/index.js
package-lock.json
package.json
src/host.ts
src/index.ts

This updates some docs that were out of date and changes the name of one public API method to make it clearer.
Since that's a breaking change and pretty much everything else we need for general use is in place, I bumped to 2.0.  There's still at least one bug to fix. I'll open a PR for that soon as well.

Release 2.0

---

README.md
client-app-example/src/client.js

I accidentally created this comment and now I can't delete it. 
Send help.

Some minor clarifications in the client docs

---

.gitignore
cli/embedded-app/.gitignore

npm's interaction with `.gitignore` is weird and poorly documented.

Fix issue with cli host app files not being included in publish.

---

package-lock.json
package.json

Someday when I'm less underwater with getting things up and running, I will look at fixing the auto-versioning in the build. Although anybody else is welcome to try in the meantime.

Bump version to fix build

---

Jenkinsfile
package-lock.json
package.json
scripts/prepare-deps.sh

This branch isn't really well-named anymore, but these changes should unblock the Jenkins build and let us publish a new version with the keyboard event features.

Change node type

---

package.json
src/client.ts
src/specs/client.spec.ts

I bumped the major version because I'd consider removal of the automatic click listener a breaking change.

Opt in click handler

---

.gitignore
README.md
cli/example-ifc.config.js
client-app-example/ifc-cli.config.js
client-app-example/public/client-app-2/index.html
package.json
src/FrameManager.ts
src/HostRouter.ts
src/elements/frame-router.ts
src/specs/FrameManager.spec.ts
src/specs/HostRouter.spec.ts
tsconfig.es5.json

Added sandbox and allow directives options for client configurations

COMUI-185 feature(ifc-config) Added sandbox and allow directives 

---

package.json
src/HostRouter.ts
src/elements/frame-router.ts

Default new path to render to about:blank when changeRoute is called with a bad / falsey value

Default to about:blank when changing route

---

Jenkinsfile

ci(jenkinsfile): update to v2 executor

---

CHANGELOG.md
package-lock.json
package.json

Bad jenkins config led to publish commits landing in this branch. merging to fix it up.

Public publication

---

Jenkinsfile
package-lock.json
package.json

removed @purecloud/web-app-deploy dependency
COMUI-393

ci(optional-dependencies): removed @purecloud/web-app-deploy dependency

---

cli/embedded-app/src/App.vue
src/FrameManager.ts

* Give html height of 100%
* Remove positioning of frame-router and iframe
* This will make only the contents of the iframe scroll as needed

fix(cli): remove embedded app dual scrollbars

---

.github/workflows/main.yml
.npmrc
Jenkinsfile
client-app-example/package-lock.json
karma.conf.js
package-lock.json
package.json

CI failed on the last merge in Jenkins, so I'm taking an opportunity while fixing it to bring over some of the general CI improvements we've made in the web component repo.

Build improvements

---

.github/workflows/main.yml
Jenkinsfile
package.json

- Add step to avoid build loops that I missed previously
- Move embedded app installs to a different npm lifecycle stage so they don't break npm publish

More Jenkins cleanup

---

.github/workflows/main.yml
Jenkinsfile
package.json

This just puts some things back the way they were before because I finally figured out what went wrong.

ci: really fix the build this time, for real, I think, probably

---

.gitignore
Jenkinsfile
README.md
doc/client-setup.md
scripts/generate-deploy-files
src/client.ts
src/messages/Lifecycle.ts
src/messages/NavRequest.ts
src/messages/Notification.ts
src/messages/Publication.ts
typedoc.js

This provides more detailed instructions on setting up a client application and adds additional
clarity to existing docs where warranted. In order to provide a sensible location for detailed doc
files, the doc ouput directory has also been moved to a new location.
COMUI-451

docs(client): improve and expand client library documentation

---

client-app-example/ifc-cli.config.js
src/FrameManager.ts
src/HostRouter.ts
src/elements/frame-router.ts
src/specs/FrameManager.spec.ts

feat(a11y): support adding a title attribute to the iframe

---

packages/iframe-coordinator/src/FrameManager.ts

fixed template string error
COMUI-1201

fix(frame-manager): fixed template string error

---

apps/ifc-example-client/main.js
packages/iframe-coordinator-cli/src/views/IframeEmbed.vue
packages/iframe-coordinator/src/client.ts
packages/iframe-coordinator/src/messages/ClientToHost.ts
packages/iframe-coordinator/src/messages/Lifecycle.ts
packages/iframe-coordinator/src/messages/NavRequest.ts
packages/iframe-coordinator/src/messages/Publication.ts
packages/iframe-coordinator/src/messages/specs/ClientToHost.spec.ts
packages/iframe-coordinator/src/specs/client.spec.ts

feat(navrequest): nav request with replace history option

---

apps/ifc-example-client/client-app-1/index.html
apps/ifc-example-client/client-app-2/index.html
apps/ifc-example-client/main.js
packages/iframe-coordinator-cli/src/views/IframeEmbed.vue
packages/iframe-coordinator/doc/client-setup.md
packages/iframe-coordinator/src/client.ts
packages/iframe-coordinator/src/messages/ClientToHost.ts
packages/iframe-coordinator/src/messages/PromptOnLeave.ts
packages/iframe-coordinator/src/messages/specs/ClientToHost.spec.ts

**Related Ticket :** https://inindca.atlassian.net/browse/COMUI-1289

feat(prompt-on-leave) - addition of prompt on leave

---

packages/iframe-coordinator/src/elements/frame-router.ts

clientConfig type fixed
COMUI-1588

fix(frame-router): clientConfig type fixed

---

Jenkinsfile
package-lock.json
package.json
packages/iframe-coordinator/package.json

remove fie dependency from published versions of cli.
COMUI-1697

fix(publish): remove fie dependency from published versions of cli

---

apps/ifc-example-client/package.json
package-lock.json
package.json

updated root and app dependencies to latest
COMUI-2545

build(dependencies): updated root and app dependencies to latest

---

Jenkinsfile
apps/ifc-example-client/package.json
package-lock.json
package.json
packages/iframe-coordinator-cli/package.json
packages/iframe-coordinator/package.json

fix(build): bumped version

---

package-lock.json
packages/iframe-coordinator/package.json

updated puppeteer to latest
COMUI-2570

chore(dependencies): updated puppeteer to latest

---

package-lock.json

build(dependency): fixed vulnerability

---

LICENSE

fix the commit message on the license update

---

package-lock.json
packages/iframe-coordinator/src/elements/frame-router.ts

move navigation to after attribute changes
COMUI-4114

fix(frame-router): move navigation to after attribute changes

---

packages/iframe-coordinator-cli/ifc-cli.js

Fix from [previous PR](https://github.com/purecloudlabs/iframe-coordinator/pull/299) rebased to resolve CI issues.

fix(ifc-cli.js): fix typo in proxy config file option configuration
