.gitignore
.npmrc
config/webpack.config.debug.js
config/webpack.config.prod.js
scripts/build.js
src/elements/component-frame.js

The custom element API spec doesn't allow modification of the DOM in the element constructor. I missed that detail, and the polyfill can't enforce that check, so things were blowing up in chrome. This fixes that issue.
Additionally, the build scripts are further improved to generate js files with the Elm debugger enabled, which are helpful for testing when embedding in other apps. 
@xdumaine @justinaray @jrrucker @JackieChiles @omarestrella @bjdupuis

Fix issue in Chrome. Build debug versions and production versions.

---

scripts/buildall.sh

Set -e option to fail the build on elm compilation errors.  Otherwise, the demo app starts unconditionally.

Fast-fail buildall script

---

README.md
src/ClientRegistry.elm
src/Path.elm

Devs who want the previous behavior can include the same prefix
as part of the client's url hash as in the route.

Strip host route from client path before navigating client.

---

js/iframe-coordinator/libs/Elm.d.ts
js/iframe-coordinator/tslint.json

I noticed an issue while merging the tslint changes.  By default tslint doesn't look for .d.ts files (https://github.com/palantir/tslint/issues/3966).
However, if you include them in your pre-commit, it will check them.  Thus the lint script was ignoring issues that the pre-commit started to look for.
This change makes it so they are consistent.

Ignore .d.ts file for tslint, since they are ignored lint script

---

js/iframe-coordinator/src/client.ts
js/iframe-coordinator/src/elements/x-ifc-frame.ts
js/iframe-coordinator/src/messages/ClientToHost.ts
js/iframe-coordinator/src/messages/HostToClient.ts
js/iframe-coordinator/src/messages/NavRequest.ts
js/iframe-coordinator/src/specs/ClientProgram.spec.ts
js/iframe-coordinator/tsconfig.json

Hopefully this illustrates what I had in mind for validation and skipping the client program. I used strict null checks for exhaustiveness checking on the union, but we could also potentially use the `never` type:
https://www.typescriptlang.org/docs/handbook/advanced-types.html#exhaustiveness-checking
Either way, I think we should leave strict null checks on. We'll have fewer bugs without it.

Discriminated union examples

---

scripts/buildall.sh
scripts/buildlibs.sh

This ensures the lockfile is used for standard runs and lets devs update the lockfile as needed through standard npm commands.

Move build scripts to npm ci instead of install

---

package.json

Accidentally had a CLI dep installed as a dev dependency.

Move accidental dev-dependency for cli to an official dependency.

---

cli/embedded-app/babel.config.js
cli/embedded-app/package-lock.json
cli/embedded-app/package.json
cli/embedded-app/src/main.ts
client-app-example/ifc-cli.config.js
client-app-example/package-lock.json
client-app-example/src/client.js
package-lock.json
package.json
tsconfig.es5.json
webpack.config.js
webpack.es5.config.js

We hit an issue in the PureCloud UI where the iframe-coordinator library wasn't IE11 compatible due to a `class` keyword. Because it's often a pain to get pre-packaged node dependencies transpiled to ES5, the best solution seemed to me to be to ship an additional es5 version in the library.

Add an ES5 build and fix issues with examples in IE11.

---

cli/embedded-app/src/views/IframeEmbed.vue
src/FrameManager.ts
src/elements/frame-router.ts

For our use case `position: relative` causes us issues and in order to override this styling in css we have to `!important` it. I would think that styling should be left completely up to the consumer of the frame-router.

A humble request

---

client-app-example/ifc-cli.config.js
client-app-example/public/client-app-1/index.html
client-app-example/public/client-app-2/index.html
client-app-example/src/client.js
src/HostRouter.ts
src/client.ts
src/elements/frame-router.ts
src/messages/Lifecycle.ts
src/messages/specs/HostToClient.spec.ts
src/specs/client.spec.ts
src/urlUtils.ts

Created a new branch for the same purpose as https://github.com/purecloudlabs/iframe-coordinator/pull/66
This time the host will still pass the `assignedRoute` data in the `"env_init"` response.
And the client will extract the `assignedRoute` from the response and store it as a private variable.
Then expose the rest env data.
And client and use `client.hostURL` getter to get the whole current host url.
Is this `client.hostURL` a good getter name?

Add route assenged as private

---

package-lock.json
package.json
src/client.ts
src/specs/FrameManager.spec.ts
src/specs/client.spec.ts

This adds an API clients can use to request navigation programmatically. It's useful for redirect-like behaviors or cases where the basic link interception provided by the client doesn't work with the client framework.

Add nav request

---

cli/embedded-app/src/views/IframeEmbed.vue
package-lock.json
package.json

The ifc-cli wrapper was failing when set up without any publish topics to listen to. Also, I fixed our one internal purecloud dependency so folks can build and run the project without having to set up artifactory.

Handle missing topics

---

src/FrameManager.ts
src/client.ts
src/messages/KeyDown.ts
src/messages/LabeledMsg.ts
src/messages/Lifecycle.ts
src/messages/NavRequest.ts
src/messages/Notification.ts
src/messages/Publication.ts
src/messages/specs/ClientToHost.spec.ts
src/messages/specs/HostToClient.spec.ts
src/specs/FrameManager.spec.ts
src/specs/client.spec.ts
tsconfig.json

This helps us not throw errors when other systems use postMessage with
data iframe-coordinator can't parse, and will provide useful details
when debugging issues.
The overall strategy here is to start including flags to indicate messages are from iframe-coordinator, and what version they were sent from.  For backwards compatibility, we don't require those fields, but we also won't throw an exception on bad messages if they aren't present.  That way we aren't throwing errors on postmessage events from other systems. 
This change also includes some improvements to the types around our internal messages, to help build some better tooling and cut down on redundancy, so you'll see a lot of generics on message types.

[COMUI-54] Add protocol and version to cross-frame messages.

---

src/messages/LabeledMsg.ts
tsconfig.json

This was apparently the result of using the requireJsonModule flag to
enable import of package.json to get the library version. It didn't get
caught locally because previous builds had already generated the type
files.

Fix issue with build not generating .d.ts type declarations.

---

cli/embedded-app/src/main.ts
package-lock.json
package.json

Just making sure when running the ifc-cli app if something fails, either due to a bug or bad data from a client app, something will be logged regardless of which browser is in use.

Improved error logging

---

cli/embedded-app/src/views/IframeEmbed.vue
cli/example-ifc.config.js
client-app-example/ifc-cli.config.js
client-app-example/public/client-app-1/index.html
client-app-example/public/client-app-2/index.html
package-lock.json
package.json

I'm working on some quality-of-life improvements for ifc-cli and this is the first one. It updates the host app to show some useful details when you navigate to a route with no assigned clients. Users will either see a list of registered client apps (with links) or a message saying no clients have been registered.

Ifc cli not found

---

README.md
cli/ifc-cli.js
client-app-example/ifc-cli.config.js
client-app-example/public/client-app-1/index.html
client-app-example/public/client-app-2/index.html
client-app-example/src/client.js
package-lock.json
package.json

This adds a built-in proxy route to `ifc-cli` so that the built in host app and local clients can live on the same domain from the browser's perspective, allowing shared localstorage and other domain-specific APIs.

Add proxy route for same-domain host and client hosting.

---

cli/embedded-app/src/views/IframeEmbed.vue

An extra pair of closing braces in the IframeEmbed view is rendering as literal text when the cli wrapper app is used.

Remove dangling }} from the IframeEmbed view

---

src/FrameManager.ts
src/client.ts
src/messages/LabeledMsg.ts
src/messages/Lifecycle.ts
src/messages/specs/ClientToHost.spec.ts
src/messages/specs/HostToClient.spec.ts
src/specs/FrameManager.spec.ts
src/specs/client.spec.ts

Cross-frame messages are now tagged as `HostToClient` or `ClientToHost` so that a frame running both
host and client code will not try to incorrectly process messages intended for the host code with
the client code and vice-versa.

feat(messaging): support nested iframes by tagging messages with direction

---

cli/embedded-app/src/router.ts
cli/embedded-app/src/views/IframeEmbed.vue

`pathMatch` would exclude the hash and query values. So instead use `fullPath` as the value for `frameRoute`.

fix(cli): missing hash and query parameters

---

package.json

17ce02633b4e3a876a53fc9a46468a41067500c3 introduced a bad commit message which
causes conventional commit linting to fail

fix(linting): update lower end commit due to bad commit message

---

src/FrameManager.ts
src/specs/FrameManager.spec.ts

Fix for https://inindca.atlassian.net/browse/COMUI-460
As suspected by @MattCheely adding the APTES attribute to the list of defaults made this work.
Tested via local build npm linked to web-directory, then opened Coaching in a version prior to the "download pdf" change.

fix(framemanager): COMUI-460 - Added new default to sandbox attributes

---

scripts/prepare-docs

I missed this path change in the previous docs update.

fix(docs): fix static asset URLs in deployed docs

---

cli/embedded-app/vue.config.js
package.json

The CLI's `help` action tries to print an example configuration file, but that file wasn't getting
included in the NPM package, so it would just error out. That file has been added to the includes in
package.json.  Additionally, the js and css asset references for the CLI embedded application have
been moved to relative paths so that the app still works correctly if proxied under a non-root path
on a domain. This can help when integrating the cli with other application build tools.

fix(cli): add missing example file to package, improve behavior when proxied

---

README.md
cli/ifc-cli.js
package.json

Instead of solely relying on devCertAuthority for certificates when using the --ssl option, allow
the consumer to specify their own ssl cert and key. If either of the two do not exist, then
devCertAuthority will be used.
COMUI-1082

feat(ifc-cli): allow consumer to specify their own ssl cert and key

---

packages/iframe-coordinator/rollup.config.js
packages/iframe-coordinator/tsconfig.json

Of course there were a couple of problems with the rollup updated that didn't manifest until the first build.
- The way I imported `package.json` in the rollup config didn't work in older versions of node 16 on the CI server
- I forgot to test the docs build locally

Fix jenkins build

---

CHANGELOG.md
package.json
scripts/sync-versions.mjs

This does a few thing to trigger the v5.0.0 release
- It removes the `beta` tags from our npm commands that were updating the version
- It fixes a problem with release tags not getting pushed back to GitHub after publication
- It removes inaccurate CHANGELOG entries generated during 5.0.0-beta period due to the tagging issue
- The 5.0.0 release should generate a correct changelog with everything new from 4.6.1 -> 5.0.0

V5 release preparation

---

packages/iframe-coordinator/doc/client-setup.md

Somewhere during the monorepo migration we accidentally killed the client setup file. I have used the powers of git to force it to rise from it's grave and work for us once again.

docs(client-setup): recover the client setup docs from the depths of time

---

packages/iframe-coordinator/src/elements/frame-router.ts

COMUI-1495
Add DOM event for `publish` message using the same format as all other client messages (except `client_started`) as an alternative to attaching listeners directly to the `messaging` emitter.

feat(frame-router): emit custom dom event for client publish messages

---

packages/iframe-coordinator/src/elements/frame-router.ts

COMUI-1648
When properties and attributes are set in a virtual DOM, the resulting frame-router events currently fire into the void. This PR adds a check to ensure the component is connected to the DOM or queues the events for when the component becomes connected.

fix(frame-router): queue events until component is connected

---

packages/iframe-coordinator/src/HostRouter.ts
packages/iframe-coordinator/src/specs/HostRouter.spec.ts

A previous attempt at fixing route specificity fixed the specific issue it was meant to address, but inadvertantly created a different source of ambiguity. This change introduces additional route sorting to resolve the issue.
COMUI-4239

fix(frame-router): fix specificity bug in route matching

---

packages/iframe-coordinator-cli/package.json

NPM will automatically pick up iframe-coordinator from the local workspace. That version gets bundled by vite/rollup when generating the package, so the dependency isn't needed at runtime either.

chore(ifc-cli): remove unnecessary explicit iframe-coordinator dependency
